### ISSUE TITLE
Backspace should not delete nodes

### ISSUE THREAD

**Issue by Planeshifter** [Planeshifter/qality.js#27]
Right now, hitting backspace will delete the selected node without warning. This makes it impossible to correct any text input and is likely too dangerous anyway. Maybe use Entf key instead, and only if the mouse is over the respective div?

**Comment by Phalanstere** [comment]
I added a delete confirmation

**Comment by Phalanstere** [comment]
Checked it again. I am still not sure if it is 100% perfect, but at least it did not happend when I used the textarea.

**Comment by Planeshifter** [comment]
Seems to be working now, I will close this issue. :smiley:
