### ISSUE TITLE
Make JSON objects more readable

### ISSUE THREAD

**Issue by Planeshifter** [Planeshifter/qality.js#31]
If we had reasonable default values defined in the reader for most of the settings, we would not need to pass in large JS objects but could only serve the important bits and the deviations from the defaults.

**Comment by Phalanstere** [comment]
hmm ... the problem is that we do no know certain parameters beforehand, for example: how many options a multiple choice node has. It's a flexible object, there I see litte chance of reducing it.
In fact, I've reduced the object size already. Only the parts which are dynamic get stored.
