### ISSUE TITLE
something strange, comma added

### ISSUE THREAD

**Issue by Phalanstere** [Planeshifter/qality.js#32]
with the new template string in the *_Multiple_Choice.node_paint *_ funtion, a comma is added which comes out of nowhere. Spent an hour or so to find out where it comes from, but to no avail.
Strange - the running internet version does not show this behaviour.
However it is really ugly.

**Comment by Phalanstere** [comment]
here is an image
![bug](http://burckhardt.ludicmedia.de/Bug01.png)

**Comment by Phalanstere** [comment]
To get rid of this I rolled back to the old notation

**Comment by Planeshifter** [comment]
My mistake: I created an array of template strings for each answer and forgot to call `join(' ')` to concatenate them together before passing the result to the template string. So it had nothing to do with the new es6 feature; I re-introduced the new notation now.
