### ISSUE TITLE
Handle overflow

### ISSUE THREAD

**Issue by Planeshifter** [Planeshifter/qality.js#7]
Handle overflow if there are more nodes in the sequence than supported by the window width.

**Comment by Phalanstere** [comment]
Mhh.. found a css problem. When I assign 100% min-width to the div and set the width to auto, it does not work. It would be nice if it was just one continous line. Now - when the line is full another one is added. It works, but is visually not very pleasing.

**Comment by Planeshifter** [comment]
Solved. Introduced an inner div with id "sequence-inner" for which the width is increased as we add further nodes.
